<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1630995583789' stop='1630995583996'>
    <name>Verifying the functionality of calculator</name>
    <title>Verifying the functionality of calculator</title>
    <test-cases>
        <test-case start='1630995583790' status='failed' stop='1630995583993'>
            <name>addition functionality</name>
            <title>addition functionality</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>ReferenceError: fs is not defined</message>
                <stack-trace>ReferenceError: fs is not defined
                    at C:\Users\IGSA937002\Desktop\ProtractorDemo\Config\conf.js:44:20
                    at ManagedPromise.invokeCallback_ (C:\Users\IGSA937002\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\IGSA937002\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\IGSA937002\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\IGSA937002\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
                    at C:\Users\IGSA937002\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at processTicksAndRejections (internal/process/task_queues.js:95:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>